# Generated by Django 4.2 on 2023-05-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('patient_id', models.CharField(max_length=8, primary_key=True, serialize=False, unique=True)),
                ('img', models.ImageField(upload_to='../static/assests')),
                ('gender', models.CharField(choices=[('SELECT', 'SELECT'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='SELECT', max_length=6)),
                ('type', models.CharField(choices=[('TYPE', 'TYPE'), ('BLOOD', 'BLOOD'), ('BREAST', 'BREAST'), ('LUNG', 'LUNG'), ('PROSTATE', 'PROSTATE'), ('SKIN', 'SKIN')], default='TYPE', max_length=15)),
                ('stage', models.CharField(choices=[('STAGE', 'STAGE'), ('EARLY', 'EARLY'), ('ADVANCED', 'ADVANCED')], default='STAGE', max_length=15)),
                ('kind', models.CharField(choices=[('KIND', 'KIND'), ('HODGKIN LYMPHOMA', 'HODGKIN LYMPHOMA'), ('NON-HODGKIN LYMPHOMA', 'NON-HODGKIN LYMPHOMA'), ('MULTIPLE LYMPHOMA', 'MULTIPLE LYMPHOMA'), ('NON-RECURRENT', 'NON-RECURRENT'), ('LOCALLY-ADVANCED', 'LOCALLY-ADVANCED'), ('RECURRENT', 'RECURRENT'), ('NON-SMALL CELL', 'NON-SMALL CELL'), ('SMALL CELL', 'SMALL CELL'), ('BASAL CELL CARCINOMA', 'BASAL CELL CARCINOMA'), ('SQUAMOUS CELL CARCINOMA', 'SQUAMOUS CELL CARCINOMA'), ('MERKEL CELL CARCINOMA', 'MERKEL CELL CARCINOMA')], default='KIND', max_length=35)),
                ('clid', models.IntegerField(default=0)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('address_a', models.TextField(max_length=60)),
                ('address_b', models.TextField(max_length=60)),
            ],
        ),
    ]
