# Generated by Django 4.2 on 2023-05-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('cname', models.CharField(max_length=30)),
                ('cemail', models.EmailField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='clid',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('', ''), ('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='img',
            field=models.ImageField(upload_to='../static/uploads'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='kind',
            field=models.CharField(choices=[('', ''), ('HODGKIN LYMPHOMA', 'HODGKIN LYMPHOMA'), ('NON-HODGKIN LYMPHOMA', 'NON-HODGKIN LYMPHOMA'), ('MULTIPLE LYMPHOMA', 'MULTIPLE LYMPHOMA'), ('NON-RECURRENT', 'NON-RECURRENT'), ('LOCALLY-ADVANCED', 'LOCALLY-ADVANCED'), ('RECURRENT', 'RECURRENT'), ('NON-SMALL CELL', 'NON-SMALL CELL'), ('SMALL CELL', 'SMALL CELL'), ('BASAL CELL CARCINOMA', 'BASAL CELL CARCINOMA'), ('SQUAMOUS CELL CARCINOMA', 'SQUAMOUS CELL CARCINOMA'), ('MERKEL CELL CARCINOMA', 'MERKEL CELL CARCINOMA')], default='', max_length=35),
        ),
        migrations.AlterField(
            model_name='patient',
            name='stage',
            field=models.CharField(choices=[('', ''), ('EARLY', 'EARLY'), ('ADVANCED', 'ADVANCED')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type',
            field=models.CharField(choices=[('', ''), ('BLOOD', 'BLOOD'), ('BREAST', 'BREAST'), ('LUNG', 'LUNG'), ('PROSTATE', 'PROSTATE'), ('SKIN', 'SKIN')], default='', max_length=15),
        ),
    ]
