# Generated by Django 4.2 on 2023-05-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_clinic_alter_patient_age_alter_patient_clid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='', max_length=6),
        ),
    ]
