# Generated by Django 4.2 on 2023-05-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0003_alter_patient_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='patient',
            name='kind',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='patient',
            name='stage',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='patient',
            name='type',
            field=models.CharField(max_length=15),
        ),
    ]
