# Generated by Django 4.2 on 2023-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_alter_patient_gender_alter_patient_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
