# Generated by Django 4.2 on 2023-05-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0005_alter_patient_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='cid',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
