# Generated by Django 4.2 on 2023-05-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0006_alter_clinic_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
