# Generated by Django 4.2 on 2023-05-01 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0007_alter_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='analysis',
            field=models.CharField(default='NA', max_length=6),
        ),
    ]
