# Generated by Django 4.2 on 2023-05-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0008_patient_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
